version: "3.7"
services: 

  db:
    image: mariadb:10
    container_name: wp-60sec-db
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - wpsite
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: wp-60sec-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: "${PMA_HOST}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - wpsite
      
  redis:
    image: redis:latest
    container_name: wp-60sec-redis
    restart: always
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - wpsite
  
  wordpress-fpm:
    #image: wordpress:5-fpm-alpine
    build: ./Dockerfiles/wp-fpm/
    image: wp-fpm:phpredis
    container_name: wp-60sec-fpm
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ./wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    networks:
      - wpsite
  
  nginx:
    image: nginx:alpine
    container_name: wp-60sec-nginx
    restart: always
    depends_on: 
      - wordpress-fpm
    ports:
      - 8085:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./wp_files:/var/www/html
    networks:
      - wpsite

networks:
  wpsite:
volumes: 
  wp_files: 
